name: New Header(s)
description: Suggest the introduction of a new header for the UltraStar file format.
title: "New Header: `#HEADER`"
labels: ["Specification"]
# FIXME: Add to project board?
body:
  - type: input
    attributes:
      label: Name of the Header(s)
      description: What is the name of the header you want to introduce?
      placeholder: Please include the name of the header in the issue title as well.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Functionality
      description: What does the header do?
      placeholder: Describe what kind of values this header contains.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Syntax
      description: What are the valid values for this header? Please use the [ABNF](https://en.wikipedia.org/wiki/Augmented_Backus–Naur_form).
      placeholder: |
        Describe the syntax of the header using ABNF.
      render: abnf
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this header needed? How does the Karaoke experience improve through this header?
      placeholder: If the header only allows a limited set of values, please explain the reasoning as well.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Provide additional information that can be useful to understand your proposal.
      placeholder: |
        Are there conflicts with existing headers?
        How does this header affect existing implementations?
        Does this header change fundamental karaoke game mechanics?
        Did you consider alternative ways to achieve the desired behavior?
